/// Flutter icons ToDoIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToDoIcons
///      fonts:
///       - asset: fonts/ToDoIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ToDoIcons {
  ToDoIcons._();

  static const _kFontFam = 'ToDoIcons';
  static const String? _kFontPkg = null;

  static const IconData icon__menu_ =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__trash_ =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__add_ =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__home_2_ =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__setting_2_ =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__tick_circle_ =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
