// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDII-W_yljEG3UNbS-SchHeH3fhTfgYwFc',
    appId: '1:866622305386:web:4187d1811ae11dc0f84613',
    messagingSenderId: '866622305386',
    projectId: 'todo-379ff',
    authDomain: 'todo-379ff.firebaseapp.com',
    storageBucket: 'todo-379ff.appspot.com',
    measurementId: 'G-DPY7R9ZL2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqdJGxMJ0SR5UKxOCOYM-8BPY9aXZ0yo',
    appId: '1:866622305386:android:c8ceffbb5d16c65bf84613',
    messagingSenderId: '866622305386',
    projectId: 'todo-379ff',
    storageBucket: 'todo-379ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3ZCyOn-xz6VpPPQYQU8ogvf0qCE6bKc',
    appId: '1:866622305386:ios:dd8900b778b0a6a0f84613',
    messagingSenderId: '866622305386',
    projectId: 'todo-379ff',
    storageBucket: 'todo-379ff.appspot.com',
    iosClientId: '866622305386-hnor3774od1em24pcoer6ntbp4alftc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3ZCyOn-xz6VpPPQYQU8ogvf0qCE6bKc',
    appId: '1:866622305386:ios:dd8900b778b0a6a0f84613',
    messagingSenderId: '866622305386',
    projectId: 'todo-379ff',
    storageBucket: 'todo-379ff.appspot.com',
    iosClientId: '866622305386-hnor3774od1em24pcoer6ntbp4alftc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
